[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "3rF7YcxqiE1VEazdwvMNS4cswGYMYT9VWRVBbt1cMphW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/trankhacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
